source "https://rubygems.org"

gem "hover", :git => "https://github.com/daviddavis/hover.git"
#gem "rest-client", "> 1.7"
group :development do
  gem "pry"
  gem "interactive_editor"
  gem "awesome_print"
  gem "pry-clipboard"
end
